# Generated by Django 5.2.7 on 2025-10-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['todo']},
        ),
    ]
