# Generated by Django 5.2.7 on 2025-11-04 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
